# Security Configuration for mypylogger v0.2.0
# This file defines the security policies and enforcement settings
# for the mypylogger project's CI/CD pipeline.

# Zero-Tolerance Security Policy Configuration
zero_tolerance_policy:
  enabled: true
  description: "Enforce zero-tolerance policy for all security vulnerabilities"
  block_pr_merge: true
  require_all_scans_pass: true
  fail_on_severity:
    - critical
    - high
    - medium
    - low
  required_scans:
    - dependency_vulnerabilities
    - code_security_analysis
    - secret_detection
    - supply_chain_security
    - configuration_validation
  
# Dependency Security Configuration
dependency_security:
  tools:
    pip_audit:
      enabled: true
      fail_on_any_vulnerability: true
      scan_transitive_dependencies: true
      output_format: "json"
    safety:
      enabled: true
      fail_on_any_vulnerability: true
      check_full_report: true
      ignore_unpinned: false
    dependabot:
      enabled: true
      auto_merge_security_updates: false
      schedule: "daily"

# Code Security Configuration  
code_security:
  codeql:
    enabled: true
    fail_on_error: true
    languages:
      - python
    query_suites:
      - security-and-quality
      - security-extended
    upload_results: true
  bandit:
    enabled: true
    fail_on_any_issue: true
    confidence_level: "low"
    severity_level: "low"
    exclude_tests: false

# Secret Detection Configuration
secret_detection:
  trufflehog:
    enabled: true
    scan_history: true
    fail_on_secrets: true
    fail_on_any_secret: true
  github_secret_scanning:
    enabled: true
    push_protection: true
    validity_checks: true

# Secret Scanning Configuration (legacy alias)
secret_scanning:
  tools:
    trufflehog:
      enabled: true
      scan_history: true
      fail_on_secrets: true
    github_secret_scanning:
      enabled: true
      push_protection: true
      validity_checks: true
    
# Vulnerability Response Configuration
vulnerability_response:
  severity_levels:
    critical:
      response_time: "1 hour"
      auto_block: true
      notify_security_team: true
    high:
      response_time: "24 hours"
      auto_block: true
      notify_maintainers: true
    medium:
      response_time: "7 days"
      auto_block: false
      create_issue: true
    low:
      response_time: "30 days"
      auto_block: false
      create_issue: false

# Security Reporting Configuration
security_reporting:
  formats:
    - json
    - sarif
    - table
    - html
    - markdown
  destinations:
    - github_security_tab
    - workflow_artifacts
    - security_team_email
  upload_locations:
    - github_security_tab
    - workflow_artifacts
    - security_team_email
  notifications:
    enabled: true
    channels:
      - security_team_email
      - github_security_tab
      - workflow_artifacts
    critical_high:
      enabled: true
      immediate: true
      block_workflow: true
      channels:
        - security_team_email
        - github_security_tab
    medium_low:
      enabled: true
      immediate: false
      block_workflow: true
      channels:
        - github_security_tab
  retention_days: 90
  include_remediation_guidance: true

# Security Monitoring and Alerting
monitoring:
  workflow_failures:
    enabled: true
    notify_on_failure: true
    escalation_time: "2 hours"
    
  performance_tracking:
    enabled: true
    track_scan_duration: true
    alert_on_degradation: true
    
  compliance_reporting:
    enabled: true
    generate_reports: true
    retention_days: 90

# Security Standards and Compliance
compliance:
  standards:
    - owasp_top_10
    - cwe_top_25
    - nist_cybersecurity_framework
    - python_security_guidelines
    - github_security_best_practices
    
  requirements:
    - "Zero known vulnerabilities"
    - "No exposed secrets"
    - "Secure coding practices"
    - "Regular security updates"
    
  audit_requirements:
    log_all_scans: true
    retain_scan_results: true
    retention_period: "1 year"
    audit_trail: true
    compliance_reporting: true
  audit_trail:
    enabled: true
    log_all_actions: true
    retention_period: "1 year"
    retention_days: 365
    include_metadata: true
    include_scan_results: true
  metrics:
    enabled: true
    track_vulnerabilities: true
    track_response_times: true
    track_resolution_time: true
    track_detection_accuracy: true
    generate_reports: true

# Emergency Response Configuration
emergency_response:
  security_team_contact: "security@mypylogger.dev"
  escalation_procedures: true
  incident_response_plan: true
  communication_channels:
    - github_issues
    - security_advisories
  critical_response:
    max_response_time: "1 hour"
    max_response_time_hours: 1
    max_resolution_time_hours: 24
    escalation_enabled: true
    auto_escalation: true
    emergency_contacts:
      - "security-lead@mypylogger.dev"
      - "devops-team@mypylogger.dev"
  high_response:
    max_response_time: "24 hours"
    notify_maintainers: true
    create_tracking_issue: true
  procedures:
    incident_response_plan: true
    escalation_matrix: true
    communication_protocols: true
    immediate_block: true
    create_security_issue: true
    notify_maintainers: true
    document_incident: true

# Audit and Logging
audit:
  log_all_scans: true
  retain_scan_results: true
  retention_period: "1 year"
  audit_trail: true

# Version and Metadata
version: "1.0.0"
last_updated: "2025-01-21"
maintained_by: "mypylogger Security Team"