name: 'Setup Python Environment'
description: 'Reusable action to set up Python with UV and caching'
inputs:
  python-version:
    description: 'Python version to set up'
    required: true
  cache-suffix:
    description: 'Suffix for cache key to avoid conflicts'
    required: false
    default: 'default'
  install-deps:
    description: 'Whether to install dependencies'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Install UV package manager
      uses: nick-invision/retry@v3
      with:
        timeout_minutes: 3
        max_attempts: 3
        retry_on: error
        command: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      shell: bash
    
    - name: Cache UV dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.local/share/uv
          ~/.cache/pip
          ~/.mypy_cache
          ~/.ruff_cache
        key: uv-${{ inputs.cache-suffix }}-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('uv.lock', 'pyproject.toml') }}
        restore-keys: |
          uv-${{ inputs.cache-suffix }}-${{ runner.os }}-${{ inputs.python-version }}-
          uv-${{ inputs.cache-suffix }}-${{ runner.os }}-
          uv-${{ runner.os }}-${{ inputs.python-version }}-
          uv-${{ runner.os }}-
    
    - name: Install project dependencies
      if: inputs.install-deps == 'true'
      uses: nick-invision/retry@v3
      with:
        timeout_minutes: 5
        max_attempts: 3
        retry_on: error
        command: |
          uv --version
          uv sync --frozen
      shell: bash
    
    - name: Verify environment
      run: |
        echo "Python version: $(uv run python --version)"
        echo "UV version: $(uv --version)"
        echo "Environment ready for Python ${{ inputs.python-version }}"
      shell: bash