name: Security Scanning

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    # Weekly security scan on Mondays at 2 AM UTC
    - cron: '0 2 * * 1'
  workflow_dispatch:

jobs:
  security-scan-matrix:
    name: Security Scan Matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scan-type: [dependencies, code-analysis, secrets]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source $HOME/.cargo/env
        
      - name: Install dependencies
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv sync
        
      - name: Run dependency security scan (pip-audit)
        if: matrix.scan-type == 'dependencies'
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv add --dev pip-audit
          mkdir -p security/reports/latest
          uv run pip-audit --format=json --output=security/reports/latest/pip-audit.json
          # Keep legacy output for compatibility
          cp security/reports/latest/pip-audit.json pip-audit-results.json
          
      - name: Run code security analysis (bandit)
        if: matrix.scan-type == 'code-analysis'
        continue-on-error: true
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv add --dev bandit
          mkdir -p security/reports/latest
          uv run bandit -r src/ -f json -o security/reports/latest/bandit.json || echo "Code analysis completed"
          # Keep legacy output for compatibility
          cp security/reports/latest/bandit.json bandit-results.json
          
      - name: Run secret detection (trufflehog)
        if: matrix.scan-type == 'secrets'
        continue-on-error: true
        run: |
          mkdir -p security/reports/latest
          docker run --rm -v "$PWD:/pwd" trufflesecurity/trufflehog:latest filesystem /pwd --json > security/reports/latest/secrets-scan.json || echo "Secret scan completed"
          # Keep legacy output for compatibility
          cp security/reports/latest/secrets-scan.json trufflehog-results.json
          
      - name: Upload security scan results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-scan-results-${{ matrix.scan-type }}
          path: "*-results.json"
          if-no-files-found: warn

  security-config-validation:
    name: Security Configuration Validation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate security configuration
        run: |
          if [ ! -f ".github/SECURITY_CONFIG.yml" ]; then
            echo "ERROR: Security configuration file missing"
            exit 1
          fi
          
      - name: Set up Python for security tools
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install UV for security check
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source $HOME/.cargo/env
          
      - name: Install dependencies for security check
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv sync
          
      - name: Run CI security check
        run: |
          chmod +x scripts/ci_security_check.sh
          export PATH="$HOME/.cargo/bin:$PATH"
          ./scripts/ci_security_check.sh

  security-findings-update:
    name: Update Security Findings
    runs-on: ubuntu-latest
    needs: [security-scan-matrix]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          
      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          source $HOME/.cargo/env
        
      - name: Install dependencies
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          uv sync
          
      - name: Download security scan results
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          pattern: security-scan-results-*
          merge-multiple: true
          
      - name: Organize scan results
        run: |
          mkdir -p security/reports/latest
          # Move downloaded results to the expected location
          if [ -f "pip-audit-results.json" ]; then
            cp pip-audit-results.json security/reports/latest/pip-audit.json
          fi
          if [ -f "bandit-results.json" ]; then
            cp bandit-results.json security/reports/latest/bandit.json
          fi
          if [ -f "trufflehog-results.json" ]; then
            cp trufflehog-results.json security/reports/latest/secrets-scan.json
          fi
          
      - name: Run security findings automation
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          python security/scripts/update-findings.py --verbose
          
      - name: Upload findings document
        uses: actions/upload-artifact@v4
        with:
          name: security-findings-document
          path: security/findings/SECURITY_FINDINGS.md
          if-no-files-found: warn
          
      - name: Upload remediation plans
        uses: actions/upload-artifact@v4
        with:
          name: security-remediation-plans
          path: security/findings/remediation-plans.yml
          if-no-files-found: warn

  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [security-scan-matrix, security-config-validation, security-findings-update]
    if: always()
    
    steps:
      - name: Download all security scan results
        uses: actions/download-artifact@v4
        continue-on-error: true
        
      - name: Download security findings document
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: security-findings-document
          
      - name: Generate security summary
        run: |
          echo "# Security Scan Summary" > security-summary.md
          echo "## Zero-Tolerance Policy Status" >> security-summary.md
          
          # Check if any scans failed
          if [ "${{ needs.security-scan-matrix.result }}" != "success" ] || [ "${{ needs.security-config-validation.result }}" != "success" ]; then
            echo "❌ SECURITY SCAN FAILED - Zero-tolerance policy violated" >> security-summary.md
            exit 1
          else
            echo "✅ All security scans passed - Zero-tolerance policy satisfied" >> security-summary.md
          fi
          
          # Include findings summary if available
          if [ -f "SECURITY_FINDINGS.md" ]; then
            echo "" >> security-summary.md
            echo "## Current Security Findings" >> security-summary.md
            cat SECURITY_FINDINGS.md >> security-summary.md
          fi
          
      - name: Upload security summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.md

  zero-tolerance:
    name: Zero-Tolerance Policy Enforcement
    runs-on: ubuntu-latest
    needs: [security-scan-matrix, security-config-validation]
    if: always()
    
    steps:
      - name: Enforce zero-tolerance policy
        run: |
          if [ "${{ needs.security-scan-matrix.result }}" != "success" ] || [ "${{ needs.security-config-validation.result }}" != "success" ]; then
            echo "❌ ZERO-TOLERANCE POLICY VIOLATION"
            echo "All security scans must pass. No exceptions."
            echo "Please fix all security issues before proceeding."
            exit 1
          fi
          echo "✅ Zero-tolerance policy satisfied"